shell:
  program: "bash"

working_directory: /path/to/working/directory

window:
  position:
    x: 100
    y: 50

  dimensions:
    columns: 110
    lines: 30

  padding:
    x: 20
    y: 15

  opacity: 0.7

font:
  normal:
    family: "Anonymice Nerd Font"
    style: Regular
  bold:
    family: "Anonymice Nerd Font"
    style: Bold
  italic:
    family: "Anonymice Nerd Font"
    style: Italic
  bold_italic:
    family: "Anonymice Nerd Font"
    style: Bold Italic
  size: 14

colors:
  cursor:
    cursor: "#ffffff"
